package vinersafe.irluncher;

import java.io.IOException;
import java.util.Random;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.*;

public class Run {
	private static Clip c;
   public void Game(String v,String f,int r,String p,String u,String c,String j) {
	   String command=null;
	   if(v.equals("1.21.3")) {
		   command = "\""+j+"\" -Xmx"+r+
		   "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
		   +c+"\\data\\000005\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
		   +c+"\\data\\1.21.3\" \"-Djna.tmpdir="
		   +c+"\\data\\1.21.3\" \"-Dorg.lwjgl.system.SharedLibraryExtractPath="
		   +c+"\\data\\1.21.3\" \"-Dio.netty.native.workdir="
		   +c+"\\data\\1.21.3\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
		   +f+"\\libraries\\com\\fasterxml\\jackson\\core\\jackson-annotations\\2.13.4\\jackson-annotations-2.13.4.jar;"
		   +f+"\\libraries\\com\\fasterxml\\jackson\\core\\jackson-core\\2.13.4\\jackson-core-2.13.4.jar;"
		   +f+"\\libraries\\com\\fasterxml\\jackson\\core\\jackson-databind\\2.13.4.2\\jackson-databind-2.13.4.2.jar;"
		   +f+"\\libraries\\com\\github\\oshi\\oshi-core\\6.4.10\\oshi-core-6.4.10.jar;"
		   +f+"\\libraries\\com\\github\\stephenc\\jcip\\jcip-annotations\\1.0-1\\jcip-annotations-1.0-1.jar;"
		   +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.10.1\\gson-2.10.1.jar;"
		   +f+"\\libraries\\com\\google\\guava\\failureaccess\\1.0.1\\failureaccess-1.0.1.jar;"
		   +f+"\\libraries\\com\\google\\guava\\guava\\32.1.2-jre\\guava-32.1.2-jre.jar;"
		   +f+"\\libraries\\com\\ibm\\icu\\icu4j\\73.2\\icu4j-73.2.jar;"
		   +f+"\\libraries\\com\\microsoft\\azure\\msal4j\\1.15.0\\msal4j-1.15.0.jar;"
		   +f+"\\libraries\\com\\mojang\\authlib\\6.0.55\\authlib-6.0.55.jar;"
		   +f+"\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar;"
		   +f+"\\libraries\\com\\mojang\\brigadier\\1.3.10\\brigadier-1.3.10.jar;"
		   +f+"\\libraries\\com\\mojang\\datafixerupper\\8.0.16\\datafixerupper-8.0.16.jar;"
		   +f+"\\libraries\\com\\mojang\\jtracy\\1.0.29\\jtracy-1.0.29.jar;"
		   +f+"\\libraries\\com\\mojang\\jtracy\\1.0.29\\jtracy-1.0.29-natives-windows.jar;"
		   +f+"\\libraries\\com\\mojang\\logging\\1.4.9\\logging-1.4.9.jar;"
		   +f+"\\libraries\\com\\mojang\\text2speech\\1.17.9\\text2speech-1.17.9.jar;"
		   +f+"\\libraries\\com\\nimbusds\\content-type\\2.3\\content-type-2.3.jar;"
		   +f+"\\libraries\\com\\nimbusds\\lang-tag\\1.7\\lang-tag-1.7.jar;"
		   +f+"\\libraries\\com\\nimbusds\\nimbus-jose-jwt\\9.37.3\\nimbus-jose-jwt-9.37.3.jar;"
		   +f+"\\libraries\\com\\nimbusds\\oauth2-oidc-sdk\\11.9.1\\oauth2-oidc-sdk-11.9.1.jar;"
		   +f+"\\libraries\\commons-codec\\commons-codec\\1.16.0\\commons-codec-1.16.0.jar;"
		   +f+"\\libraries\\commons-io\\commons-io\\2.15.1\\commons-io-2.15.1.jar;"
		   +f+"\\libraries\\commons-logging\\commons-logging\\1.2\\commons-logging-1.2.jar;"
		   +f+"\\libraries\\io\\netty\\netty-buffer\\4.1.97.Final\\netty-buffer-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-codec\\4.1.97.Final\\netty-codec-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-common\\4.1.97.Final\\netty-common-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-handler\\4.1.97.Final\\netty-handler-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-resolver\\4.1.97.Final\\netty-resolver-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-transport-classes-epoll\\4.1.97.Final\\netty-transport-classes-epoll-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-transport-native-unix-common\\4.1.97.Final\\netty-transport-native-unix-common-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-transport\\4.1.97.Final\\netty-transport-4.1.97.Final.jar;"
		   +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.12\\fastutil-8.5.12.jar;"
		   +f+"\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.14.0\\jna-platform-5.14.0.jar;"
		   +f+"\\libraries\\net\\java\\dev\\jna\\jna\\5.14.0\\jna-5.14.0.jar;"
		   +f+"\\libraries\\net\\minidev\\accessors-smart\\2.5.0\\accessors-smart-2.5.0.jar;"
		   +f+"\\libraries\\net\\minidev\\json-smart\\2.5.0\\json-smart-2.5.0.jar;"
		   +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;"
		   +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.26.0\\commons-compress-1.26.0.jar;"
		   +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.14.0\\commons-lang3-3.14.0.jar;"
		   +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.13\\httpclient-4.5.13.jar;"
		   +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.16\\httpcore-4.4.16.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.22.1\\log4j-api-2.22.1.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.22.1\\log4j-core-2.22.1.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j2-impl\\2.22.1\\log4j-slf4j2-impl-2.22.1.jar;"
		   +f+"\\libraries\\org\\jcraft\\jorbis\\0.0.17\\jorbis-0.0.17.jar;"
		   +f+"\\libraries\\org\\joml\\joml\\1.10.5\\joml-1.10.5.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lz4\\lz4-java\\1.8.0\\lz4-java-1.8.0.jar;"
		   +f+"\\libraries\\org\\ow2\\asm\\asm\\9.3\\asm-9.3.jar;"
		   +f+"\\libraries\\org\\slf4j\\slf4j-api\\2.0.9\\slf4j-api-2.0.9.jar;"
		   +f+"\\versions\\1.21.3\\1.21.3.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.21.3 --gameDir \""
		   +f+"\" --assetsDir \""+f+"\\assets\" --assetIndex 18 --uuid "
		   +u+" --accessToken 1337535510N --clientId ${clientid} --xuid ${auth_xuid} --userType legacy --versionType release";
	   }else if(v.equals("1.20.6")) {
		   command = "\""+j+"\" -Xmx"+r+
		   "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
		   +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
		   +c+"\\data\\1.21.3\" \"-Djna.tmpdir="
		   +c+"\\data\\1.21.3\" \"-Dorg.lwjgl.system.SharedLibraryExtractPath="
		   +c+"\\data\\1.21.3\" \"-Dio.netty.native.workdir="
		   +c+"\\data\\1.21.3\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
		   +f+"\\libraries\\com\\github\\oshi\\oshi-core\\6.4.10\\oshi-core-6.4.10.jar;"
		   +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.10.1\\gson-2.10.1.jar;"
		   +f+"\\libraries\\com\\google\\guava\\failureaccess\\1.0.1\\failureaccess-1.0.1.jar;"
		   +f+"\\libraries\\com\\google\\guava\\guava\\32.1.2-jre\\guava-32.1.2-jre.jar;"
		   +f+"\\libraries\\com\\ibm\\icu\\icu4j\\73.2\\icu4j-73.2.jar;"
		   +f+"\\libraries\\com\\mojang\\authlib\\6.0.54\\authlib-6.0.54.jar;"
		   +f+"\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar;"
		   +f+"\\libraries\\com\\mojang\\brigadier\\1.2.9\\brigadier-1.2.9.jar;"
		   +f+"\\libraries\\com\\mojang\\datafixerupper\\7.0.14\\datafixerupper-7.0.14.jar;"
		   +f+"\\libraries\\com\\mojang\\logging\\1.2.7\\logging-1.2.7.jar;"
		   +f+"\\libraries\\com\\mojang\\text2speech\\1.17.9\\text2speech-1.17.9.jar;"
		   +f+"\\libraries\\commons-codec\\commons-codec\\1.16.0\\commons-codec-1.16.0.jar;"
		   +f+"\\libraries\\commons-io\\commons-io\\2.15.1\\commons-io-2.15.1.jar;"
		   +f+"\\libraries\\commons-logging\\commons-logging\\1.2\\commons-logging-1.2.jar;"
		   +f+"\\libraries\\io\\netty\\netty-buffer\\4.1.97.Final\\netty-buffer-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-codec\\4.1.97.Final\\netty-codec-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-common\\4.1.97.Final\\netty-common-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-handler\\4.1.97.Final\\netty-handler-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-resolver\\4.1.97.Final\\netty-resolver-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-transport-classes-epoll\\4.1.97.Final\\netty-transport-classes-epoll-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-transport-native-unix-common\\4.1.97.Final\\netty-transport-native-unix-common-4.1.97.Final.jar;"
		   +f+"\\libraries\\io\\netty\\netty-transport\\4.1.97.Final\\netty-transport-4.1.97.Final.jar;"
		   +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.12\\fastutil-8.5.12.jar;"
		   +f+"\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.14.0\\jna-platform-5.14.0.jar;"
		   +f+"\\libraries\\net\\java\\dev\\jna\\jna\\5.14.0\\jna-5.14.0.jar;"
		   +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;"
		   +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.26.0\\commons-compress-1.26.0.jar;"
		   +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.14.0\\commons-lang3-3.14.0.jar;"
		   +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.13\\httpclient-4.5.13.jar;"
		   +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.16\\httpcore-4.4.16.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.22.1\\log4j-api-2.22.1.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.22.1\\log4j-core-2.22.1.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j2-impl\\2.22.1\\log4j-slf4j2-impl-2.22.1.jar;"
		   +f+"\\libraries\\org\\jcraft\\jorbis\\0.0.17\\jorbis-0.0.17.jar;"
		   +f+"\\libraries\\org\\joml\\joml\\1.10.5\\joml-1.10.5.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3-natives-windows.jar;"
		   +f+"\\libraries\\org\\lz4\\lz4-java\\1.8.0\\lz4-java-1.8.0.jar;"
		   +f+"\\libraries\\org\\slf4j\\slf4j-api\\2.0.9\\slf4j-api-2.0.9.jar;"
		   +f+"\\versions\\1.20.6\\1.20.6.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.20.6 --gameDir \""
		   +f+"\" --assetsDir \""+f+"\\assets\" --assetIndex 16 --uuid "
		   +u+" --accessToken 1337535510N --clientId ${clientid} --xuid ${auth_xuid} --userType legacy --versionType release";
	   }else if(v.equals("1.20.4")) {
    	   command = "\""+j+"\" -Xmx"+r+
    	   "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
    	   +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
    	   +c+"\\data\\1.21.3\" \"-Djna.tmpdir="
    	   +c+"\\data\\1.21.3\" \"-Dorg.lwjgl.system.SharedLibraryExtractPath="
    	   +c+"\\data\\1.21.3\" \"-Dio.netty.native.workdir="
    	   +c+"\\data\\1.21.3\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
    	   +f+"\\libraries\\com\\github\\oshi\\oshi-core\\6.4.5\\oshi-core-6.4.5.jar;"
           +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.10.1\\gson-2.10.1.jar;"
    	   +f+"\\libraries\\com\\google\\guava\\failureaccess\\1.0.1\\failureaccess-1.0.1.jar;"
           +f+"\\libraries\\com\\google\\guava\\guava\\32.1.2-jre\\guava-32.1.2-jre.jar;"
    	   +f+"\\libraries\\com\\ibm\\icu\\icu4j\\73.2\\icu4j-73.2.jar;"
           +f+"\\libraries\\com\\mojang\\authlib\\6.0.52\\authlib-6.0.52.jar;"
    	   +f+"\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar;"
           +f+"\\libraries\\com\\mojang\\brigadier\\1.2.9\\brigadier-1.2.9.jar;"
    	   +f+"\\libraries\\com\\mojang\\datafixerupper\\6.0.8\\datafixerupper-6.0.8.jar;"
           +f+"\\libraries\\com\\mojang\\logging\\1.1.1\\logging-1.1.1.jar;"
    	   +f+"\\libraries\\com\\mojang\\text2speech\\1.17.9\\text2speech-1.17.9.jar;"
           +f+"\\libraries\\commons-codec\\commons-codec\\1.16.0\\commons-codec-1.16.0.jar;"
    	   +f+"\\libraries\\commons-io\\commons-io\\2.13.0\\commons-io-2.13.0.jar;"
           +f+"\\libraries\\commons-logging\\commons-logging\\1.2\\commons-logging-1.2.jar;"
    	   +f+"\\libraries\\io\\netty\\netty-buffer\\4.1.97.Final\\netty-buffer-4.1.97.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-codec\\4.1.97.Final\\netty-codec-4.1.97.Final.jar;"
    	   +f+"\\libraries\\io\\netty\\netty-common\\4.1.97.Final\\netty-common-4.1.97.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-handler\\4.1.97.Final\\netty-handler-4.1.97.Final.jar;"
    	   +f+"\\libraries\\io\\netty\\netty-resolver\\4.1.97.Final\\netty-resolver-4.1.97.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport-classes-epoll\\4.1.97.Final\\netty-transport-classes-epoll-4.1.97.Final.jar;"
    	   +f+"\\libraries\\io\\netty\\netty-transport-native-unix-common\\4.1.97.Final\\netty-transport-native-unix-common-4.1.97.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport\\4.1.97.Final\\netty-transport-4.1.97.Final.jar;"
    	   +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.12\\fastutil-8.5.12.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.13.0\\jna-platform-5.13.0.jar;"
    	   +f+"\\libraries\\net\\java\\dev\\jna\\jna\\5.13.0\\jna-5.13.0.jar;"
           +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;"
    	   +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.22\\commons-compress-1.22.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.13.0\\commons-lang3-3.13.0.jar;"
    	   +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.13\\httpclient-4.5.13.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.16\\httpcore-4.4.16.jar;"
    	   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.19.0\\log4j-api-2.19.0.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.19.0\\log4j-core-2.19.0.jar;"
    	   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j2-impl\\2.19.0\\log4j-slf4j2-impl-2.19.0.jar;"
           +f+"\\libraries\\org\\joml\\joml\\1.10.5\\joml-1.10.5.jar;"
    	   +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.2\\lwjgl-glfw-3.3.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.2\\lwjgl-glfw-3.3.2-natives-windows.jar;"
    	   +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.2\\lwjgl-jemalloc-3.3.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.2\\lwjgl-jemalloc-3.3.2-natives-windows.jar;"
    	   +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.2\\lwjgl-openal-3.3.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.2\\lwjgl-openal-3.3.2-natives-windows.jar;"
    	   +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.2\\lwjgl-opengl-3.3.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.2\\lwjgl-opengl-3.3.2-natives-windows.jar;"
    	   +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.2\\lwjgl-stb-3.3.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.2\\lwjgl-stb-3.3.2-natives-windows.jar;"
    	   +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.2\\lwjgl-tinyfd-3.3.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.2\\lwjgl-tinyfd-3.3.2-natives-windows.jar;"
    	   +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.2\\lwjgl-3.3.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.2\\lwjgl-3.3.2-natives-windows.jar;"
    	   +f+"\\libraries\\org\\slf4j\\slf4j-api\\2.0.7\\slf4j-api-2.0.7.jar;"
           +f+"\\versions\\1.20.4\\1.20.4.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.20.4 --gameDir \""
    	   +f+"\" --assetsDir \""+f+"\\assets\" --assetIndex 12 --uuid "
    	   +u+" --accessToken 1337535510N --clientId ${clientid} --xuid ${auth_xuid} --userType legacy --versionType release";
       }else if(v.equals("1.20.1")) {
    	   command = "\""+j+"\" -Xmx"+r+
           "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
           +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
           +c+"\\data\\1.19-1.20\" \"-Djna.tmpdir="
           +c+"\\data\\1.19-1.20\" \"-Dorg.lwjgl.system.SharedLibraryExtractPath="
           +c+"\\data\\1.19-1.20\" \"-Dio.netty.native.workdir="
           +c+"\\data\\1.19-1.20\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
           +f+"\\libraries\\com\\github\\oshi\\oshi-core\\6.2.2\\oshi-core-6.2.2.jar;"
           +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.10\\gson-2.10.jar;"
           +f+"\\libraries\\com\\google\\guava\\failureaccess\\1.0.1\\failureaccess-1.0.1.jar;"
           +f+"\\libraries\\com\\google\\guava\\guava\\31.1-jre\\guava-31.1-jre.jar;"
           +f+"\\libraries\\com\\ibm\\icu\\icu4j\\71.1\\icu4j-71.1.jar;"
           +f+"\\libraries\\com\\mojang\\authlib\\4.0.43\\authlib-4.0.43.jar;"
           +f+"\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar;"
           +f+"\\libraries\\com\\mojang\\brigadier\\1.1.8\\brigadier-1.1.8.jar;"
           +f+"\\libraries\\com\\mojang\\datafixerupper\\6.0.8\\datafixerupper-6.0.8.jar;"
           +f+"\\libraries\\com\\mojang\\logging\\1.1.1\\logging-1.1.1.jar;"
           +f+"\\libraries\\com\\mojang\\text2speech\\1.17.9\\text2speech-1.17.9.jar;"
           +f+"\\libraries\\commons-codec\\commons-codec\\1.15\\commons-codec-1.15.jar;"
           +f+"\\libraries\\commons-io\\commons-io\\2.11.0\\commons-io-2.11.0.jar;"
           +f+"\\libraries\\commons-logging\\commons-logging\\1.2\\commons-logging-1.2.jar;"
           +f+"\\libraries\\io\\netty\\netty-buffer\\4.1.82.Final\\netty-buffer-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-codec\\4.1.82.Final\\netty-codec-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-common\\4.1.82.Final\\netty-common-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-handler\\4.1.82.Final\\netty-handler-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-resolver\\4.1.82.Final\\netty-resolver-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport-classes-epoll\\4.1.82.Final\\netty-transport-classes-epoll-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport-native-unix-common\\4.1.82.Final\\netty-transport-native-unix-common-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport\\4.1.82.Final\\netty-transport-4.1.82.Final.jar;"
           +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.9\\fastutil-8.5.9.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.12.1\\jna-platform-5.12.1.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna\\5.12.1\\jna-5.12.1.jar;"
           +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.21\\commons-compress-1.21.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.12.0\\commons-lang3-3.12.0.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.13\\httpclient-4.5.13.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.15\\httpcore-4.4.15.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.19.0\\log4j-api-2.19.0.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.19.0\\log4j-core-2.19.0.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j2-impl\\2.19.0\\log4j-slf4j2-impl-2.19.0.jar;"
           +f+"\\libraries\\org\\joml\\joml\\1.10.5\\joml-1.10.5.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.1\\lwjgl-glfw-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.1\\lwjgl-jemalloc-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.1\\lwjgl-openal-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.1\\lwjgl-opengl-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.1\\lwjgl-stb-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.1\\lwjgl-tinyfd-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.1\\lwjgl-3.3.1.jar;"
           +f+"\\libraries\\org\\slf4j\\slf4j-api\\2.0.1\\slf4j-api-2.0.1.jar;"
           +f+"\\versions\\1.20.1\\1.20.1.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.20.1 --gameDir \""
           +f+"\" --assetsDir \""
           +f+"\\assets\" --assetIndex 5 --uuid "
           +u+" --accessToken 1337535510N --clientId ${clientid} --xuid ${auth_xuid} --userType legacy --versionType release";
       }else if(v.equals("1.19.4")) {
    	   command = "\""+j+"\" -Xmx"+r+
           "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
           +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
           +c+"\\data\\1.19-1.20\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
           +f+"\\libraries\\com\\github\\oshi\\oshi-core\\6.2.2\\oshi-core-6.2.2.jar;"
           +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.10\\gson-2.10.jar;"
           +f+"\\libraries\\com\\google\\guava\\failureaccess\\1.0.1\\failureaccess-1.0.1.jar;"
           +f+"\\libraries\\com\\google\\guava\\guava\\31.1-jre\\guava-31.1-jre.jar;"
           +f+"\\libraries\\com\\ibm\\icu\\icu4j\\71.1\\icu4j-71.1.jar;"
           +f+"\\libraries\\com\\mojang\\authlib\\3.18.38\\authlib-3.18.38.jar;"
           +f+"\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar;"
           +f+"\\libraries\\com\\mojang\\brigadier\\1.0.18\\brigadier-1.0.18.jar;"
           +f+"\\libraries\\com\\mojang\\datafixerupper\\6.0.6\\datafixerupper-6.0.6.jar;"
           +f+"\\libraries\\com\\mojang\\logging\\1.1.1\\logging-1.1.1.jar;"
           +f+"\\libraries\\com\\mojang\\text2speech\\1.16.7\\text2speech-1.16.7.jar;"
           +f+"\\libraries\\commons-codec\\commons-codec\\1.15\\commons-codec-1.15.jar;"
           +f+"\\libraries\\commons-io\\commons-io\\2.11.0\\commons-io-2.11.0.jar;"
           +f+"\\libraries\\commons-logging\\commons-logging\\1.2\\commons-logging-1.2.jar;"
           +f+"\\libraries\\io\\netty\\netty-buffer\\4.1.82.Final\\netty-buffer-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-codec\\4.1.82.Final\\netty-codec-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-common\\4.1.82.Final\\netty-common-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-handler\\4.1.82.Final\\netty-handler-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-resolver\\4.1.82.Final\\netty-resolver-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport-classes-epoll\\4.1.82.Final\\netty-transport-classes-epoll-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport-native-unix-common\\4.1.82.Final\\netty-transport-native-unix-common-4.1.82.Final.jar;"
           +f+"\\libraries\\io\\netty\\netty-transport\\4.1.82.Final\\netty-transport-4.1.82.Final.jar;"
           +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.9\\fastutil-8.5.9.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.12.1\\jna-platform-5.12.1.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna\\5.12.1\\jna-5.12.1.jar;"
           +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.21\\commons-compress-1.21.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.12.0\\commons-lang3-3.12.0.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.13\\httpclient-4.5.13.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.15\\httpcore-4.4.15.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.19.0\\log4j-api-2.19.0.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.19.0\\log4j-core-2.19.0.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j2-impl\\2.19.0\\log4j-slf4j2-impl-2.19.0.jar;"
           +f+"\\libraries\\org\\joml\\joml\\1.10.5\\joml-1.10.5.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.1\\lwjgl-glfw-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.1\\lwjgl-jemalloc-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.1\\lwjgl-openal-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.1\\lwjgl-opengl-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.1\\lwjgl-stb-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.1\\lwjgl-tinyfd-3.3.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.3.1\\lwjgl-3.3.1.jar;"
           +f+"\\libraries\\org\\slf4j\\slf4j-api\\2.0.1\\slf4j-api-2.0.1.jar;"
           +f+"\\versions\\1.19.4\\1.19.4.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.19.4 --gameDir \""
           +f+"\" --assetsDir \""
           +f+"\\assets\" --assetIndex 3 --uuid "
           +u+" --accessToken 1337535510N --clientId ${clientid} --xuid ${auth_xuid} --userType legacy --versionType release";
    	}else if(v.equals("1.18.2")) {
    	   	command = "\""+j+"\" -Xmx"+r+
           "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
           +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
           +c+"\\data\\1.14-1.18\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
           +f+"\\libraries\\com\\mojang\\logging\\1.0.0\\logging-1.0.0.jar;"
           +f+"\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar;"
           +f+"\\libraries\\com\\github\\oshi\\oshi-core\\5.8.5\\oshi-core-5.8.5.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna\\5.10.0\\jna-5.10.0.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.10.0\\jna-platform-5.10.0.jar;"
           +f+"\\libraries\\org\\slf4j\\slf4j-api\\1.8.0-beta4\\slf4j-api-1.8.0-beta4.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j18-impl\\2.17.0\\log4j-slf4j18-impl-2.17.0.jar;"
           +f+"\\libraries\\com\\ibm\\icu\\icu4j\\70.1\\icu4j-70.1.jar;"
           +f+"\\libraries\\com\\mojang\\javabridge\\1.2.24\\javabridge-1.2.24.jar;"
           +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;"
           +f+"\\libraries\\io\\netty\\netty-all\\4.1.68.Final\\netty-all-4.1.68.Final.jar;"
           +f+"\\libraries\\com\\google\\guava\\failureaccess\\1.0.1\\failureaccess-1.0.1.jar;"
           +f+"\\libraries\\com\\google\\guava\\guava\\31.0.1-jre\\guava-31.0.1-jre.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.12.0\\commons-lang3-3.12.0.jar;"
           +f+"\\libraries\\commons-io\\commons-io\\2.11.0\\commons-io-2.11.0.jar;"
           +f+"\\libraries\\commons-codec\\commons-codec\\1.15\\commons-codec-1.15.jar;"
           +f+"\\libraries\\com\\mojang\\brigadier\\1.0.18\\brigadier-1.0.18.jar;"
           +f+"\\libraries\\com\\mojang\\datafixerupper\\4.1.27\\datafixerupper-4.1.27.jar;"
           +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.8.9\\gson-2.8.9.jar;"
           +f+"\\libraries\\com\\mojang\\authlib\\3.3.39\\authlib-3.3.39.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.21\\commons-compress-1.21.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.13\\httpclient-4.5.13.jar;"
           +f+"\\libraries\\commons-logging\\commons-logging\\1.2\\commons-logging-1.2.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.14\\httpcore-4.4.14.jar;"
           +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.6\\fastutil-8.5.6.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.17.0\\log4j-api-2.17.0.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.17.0\\log4j-core-2.17.0.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.2.2\\lwjgl-tinyfd-3.2.2.jar;"
           +f+"\\libraries\\com\\mojang\\text2speech\\1.12.4\\text2speech-1.12.4.jar;"
           +f+"\\versions\\1.18.2\\1.18.2.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.18.2 --gameDir \""
           +f+"\" --assetsDir \""
           +f+"\\assets\" --assetIndex 1.18 --uuid "
           +u+" --accessToken 1337535510N --clientId ${clientid} --xuid ${auth_xuid} --userType legacy --versionType release";
    	}else if(v.equals("1.17.1")) {
    	   command = "\""+j+"\" -Xmx"+r+
           "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
           +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
           +c+"\\data\\1.14-1.18\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
           +f+"\\libraries\\com\\mojang\\blocklist\\1.0.5\\blocklist-1.0.5.jar;"
           +f+"\\libraries\\com\\github\\oshi\\oshi-core\\5.7.5\\oshi-core-5.7.5.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna\\5.8.0\\jna-5.8.0.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.8.0\\jna-platform-5.8.0.jar;"
           +f+"\\libraries\\org\\slf4j\\slf4j-api\\1.8.0-beta4\\slf4j-api-1.8.0-beta4.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j18-impl\\2.14.1\\log4j-slf4j18-impl-2.14.1.jar;"
           +f+"\\libraries\\com\\ibm\\icu\\icu4j\\66.1\\icu4j-66.1.jar;"
           +f+"\\libraries\\com\\mojang\\javabridge\\1.1.23\\javabridge-1.1.23.jar;"
           +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.3\\jopt-simple-5.0.3.jar;"
           +f+"\\libraries\\io\\netty\\netty-all\\4.1.25.Final\\netty-all-4.1.25.Final.jar;"
           +f+"\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;"
           +f+"\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;"
           +f+"\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;"
           +f+"\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;"
           +f+"\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;"
           +f+"\\libraries\\com\\mojang\\brigadier\\1.0.18\\brigadier-1.0.18.jar;"
           +f+"\\libraries\\com\\mojang\\datafixerupper\\4.0.26\\datafixerupper-4.0.26.jar;"
           +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;"
           +f+"\\libraries\\com\\mojang\\authlib\\2.3.31\\authlib-2.3.31.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;"
           +f+"\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;"
           +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.2.1\\fastutil-8.2.1.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.14.1\\log4j-api-2.14.1.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.14.1\\log4j-core-2.14.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.2.2\\lwjgl-tinyfd-3.2.2.jar;"
           +f+"\\libraries\\com\\mojang\\text2speech\\1.11.3\\text2speech-1.11.3.jar;"
           +f+"\\versions\\1.17.1\\1.17.1.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.17.1 --gameDir \""
           +f+"\" --assetsDir \""
           +f+"\\assets\" --assetIndex 1.17 --uuid "
           +u+" --accessToken 1337535510N --userType legacy --versionType release";
    	 }else if(v.equals("1.16.5")) {
  		   command ="\""+j+"\" -Xmx"+r+
           "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
           +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
           +c+"\\data\\1.14-1.18\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
           +f+"\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna\\4.4.0\\jna-4.4.0.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar;"
           +f+"\\libraries\\com\\ibm\\icu\\icu4j\\66.1\\icu4j-66.1.jar;"
           +f+"\\libraries\\com\\mojang\\javabridge\\1.0.22\\javabridge-1.0.22.jar;"
           +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.3\\jopt-simple-5.0.3.jar;"
           +f+"\\libraries\\io\\netty\\netty-all\\4.1.25.Final\\netty-all-4.1.25.Final.jar;"
           +f+"\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;"
           +f+"\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;"
           +f+"\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;"
           +f+"\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;"
           +f+"\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;"
           +f+"\\libraries\\com\\mojang\\brigadier\\1.0.17\\brigadier-1.0.17.jar;"
           +f+"\\libraries\\com\\mojang\\datafixerupper\\4.0.26\\datafixerupper-4.0.26.jar;"
           +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;"
           +f+"\\libraries\\com\\mojang\\authlib\\2.1.28\\authlib-2.1.28.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;"
           +f+"\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;"
           +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.2.1\\fastutil-8.2.1.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.8.1\\log4j-api-2.8.1.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.8.1\\log4j-core-2.8.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.2.2\\lwjgl-tinyfd-3.2.2.jar;"
           +f+"\\libraries\\com\\mojang\\text2speech\\1.11.3\\text2speech-1.11.3.jar;"
           +f+"\\versions\\1.16.5\\1.16.5.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.16.5 --gameDir \""
           +f+"\" --assetsDir \""
           +f+"\\assets\" --assetIndex 1.16 --uuid "
           +u+" --accessToken 1337535510N --userType legacy --versionType release";
       }else if(v.equals("1.15.2")) {
 		   command="\""+j+"\" -Xmx"+r+
           "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
           +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
           +c+"\\data\\1.14-1.18\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
           +f+"\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\jna\\4.4.0\\jna-4.4.0.jar;"
           +f+"\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar;"
           +f+"\\libraries\\com\\ibm\\icu\\icu4j-core-mojang\\51.2\\icu4j-core-mojang-51.2.jar;"
           +f+"\\libraries\\com\\mojang\\javabridge\\1.0.22\\javabridge-1.0.22.jar;"
           +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.3\\jopt-simple-5.0.3.jar;"
           +f+"\\libraries\\io\\netty\\netty-all\\4.1.25.Final\\netty-all-4.1.25.Final.jar;"
           +f+"\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;"
           +f+"\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;"
           +f+"\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;"
           +f+"\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;"
           +f+"\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;"
           +f+"\\libraries\\com\\mojang\\brigadier\\1.0.17\\brigadier-1.0.17.jar;"
           +f+"\\libraries\\com\\mojang\\datafixerupper\\2.0.24\\datafixerupper-2.0.24.jar;"
           +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;"
           +f+"\\libraries\\com\\mojang\\authlib\\1.5.25\\authlib-1.5.25.jar;"
           +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;"
           +f+"\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;"
           +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;"
           +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.2.1\\fastutil-8.2.1.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.8.1\\log4j-api-2.8.1.jar;"
           +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.8.1\\log4j-core-2.8.1.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;"
           +f+"\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.2.2\\lwjgl-tinyfd-3.2.2.jar;"
           +f+"\\libraries\\com\\mojang\\text2speech\\1.11.3\\text2speech-1.11.3.jar;"
           +f+"\\versions\\1.15.2\\1.15.2.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.15.2 --gameDir \""
           +f+"\" --assetsDir \""
           +f+"\\assets\" --assetIndex 1.15 --uuid "
           +u+" --accessToken 1337535510N --userType legacy --versionType release";
       }else if(v.equals("1.14.4")) {
		   command="\""+j+"\" -Xmx"+r+
		   "G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M \"-Dlog4j.configurationFile="
		   +c+"\\data\\000000\" -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump \"-Djava.library.path="
		   +c+"\\data\\1.14-1.18\" -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=unknown -cp \""
		   +f+"\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar;"
		   +f+"\\libraries\\net\\java\\dev\\jna\\jna\\4.4.0\\jna-4.4.0.jar;"
		   +f+"\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar;"
		   +f+"\\libraries\\com\\ibm\\icu\\icu4j-core-mojang\\51.2\\icu4j-core-mojang-51.2.jar;"
		   +f+"\\libraries\\com\\mojang\\javabridge\\1.0.22\\javabridge-1.0.22.jar;"
		   +f+"\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.3\\jopt-simple-5.0.3.jar;"
		   +f+"\\libraries\\io\\netty\\netty-all\\4.1.25.Final\\netty-all-4.1.25.Final.jar;"
		   +f+"\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;"
		   +f+"\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;"
		   +f+"\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;"
		   +f+"\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;"
		   +f+"\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;"
		   +f+"\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;"
		   +f+"\\libraries\\com\\mojang\\brigadier\\1.0.17\\brigadier-1.0.17.jar;"
		   +f+"\\libraries\\com\\mojang\\datafixerupper\\2.0.24\\datafixerupper-2.0.24.jar;"
		   +f+"\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;"
		   +f+"\\libraries\\com\\mojang\\authlib\\1.5.25\\authlib-1.5.25.jar;"
		   +f+"\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;"
		   +f+"\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;"
		   +f+"\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;"
		   +f+"\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;"
		   +f+"\\libraries\\it\\unimi\\dsi\\fastutil\\8.2.1\\fastutil-8.2.1.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.8.1\\log4j-api-2.8.1.jar;"
		   +f+"\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.8.1\\log4j-core-2.8.1.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;"
		   +f+"\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;"
		   +f+"\\libraries\\com\\mojang\\text2speech\\1.11.3\\text2speech-1.11.3.jar;"
		   +f+"\\versions\\1.14.4\\1.14.4.jar\" net.minecraft.client.main.Main --username "+p+" --version 1.14.4 --gameDir \""
		   +f+"\" --assetsDir \""
		   +f+"\\assets\" --assetIndex 1.14 --uuid "
		   +u+" --accessToken 1337535510N --userType legacy --versionType release";
	   }
	   System.out.println(command);
        try {
        	ProcessBuilder processBuilder = new ProcessBuilder(command.split(" "));
            processBuilder.inheritIO();
            processBuilder.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
   public void Music() {
	   int a=new Random().nextInt(3) + 2;
	   System.out.println(a);
	   try {
		   
		    AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource
		    ("/data/00000"+a));
		    
		    Clip clip = AudioSystem.getClip();
		    c = clip;
		    clip.open(audioInputStream);
		    clip.loop(Clip.LOOP_CONTINUOUSLY);
		    Volume(0.3f);
		} catch (Exception e) {
		    e.printStackTrace();
		}
   }
   public void Volume(float input) {
	   try {
		   	
	        FloatControl volumeControl = (FloatControl) c.getControl(FloatControl.Type.MASTER_GAIN);
	        
	        // Calculate the desired volume level
	        float minGain = volumeControl.getMinimum()+50;
	        float maxGain = volumeControl.getMaximum()-5.0205998f;
	        float volume = (maxGain - minGain) * input + minGain; // Adjust volume here
	        
	        // Set the volume within allowed range
	        volume = Math.max(volume, minGain);
	        volume = Math.min(volume, maxGain);
	        if(input!=0) {
	        	volumeControl.setValue(volume);
	        } else volumeControl.setValue(-80);

	    } catch (Exception e) {
	        e.printStackTrace();
	    }
	   }
}